### ISSUE TITLE
Not showing in sidebar as active

### ISSUE THREAD

**Issue by trippinshrumes** [albfan/terminator#10]
ubuntu 17.10
kernel 4.14
Terminator 1.91-1 (Also tried 1.90-0)

I've attempted doing a search on this issue, but as I'm not able to describe it the best it has hindered my search from finding anything resourceful. 

When I open terminator terminal, an icon shows up on my sidebar, I am able to favorite it aswell...

Although it does not detect that terminal has an open window, if I do not have terminator as a favorite, the icon that shows up on the sidebar, if clicked on will launch another terminator terminal but then the icon dissapears from the sidebar.

If I do have terminator favorited, and any amount of terminator windows open, it does not actually detect that the windows are open, in such, clicking the terminator icon will only launch more windows.

I use a lot of work spaces, and I have terminator full screened in it's own workspace, although I would like clicking terminator to take me to the active window.

What can I do to resolve this and how can something like a window not being detected be properly described? thanks.

**Comment by albfan** [comment]
See this is not an official repo for terminator.

Anyway maybe you want to upload a screencast with your problem. I cannot understand it with your description

**Comment by trippinshrumes** [comment]
I have attached an image. You will see that next to the terminator icon on the sidebar, it is not putting circles next to it indicating there is an open window. I have open 4 file screens, and have demonstrated how clicking on it will give me an option between the 4 screens. This does not work for terminator.

![screenshot from 2017-11-18 10-23-43](https://user-images.githubusercontent.com/13083581/32982505-66a1db2a-cc4b-11e7-8f8a-75da50a0353d.png)

**Comment by albfan** [comment]
Got it. That's a GNOME shell feature I guess. I'm asking about it on IRC. Try to investigate about it by yourself (what kind of integration and app needs). This is the typical problem about ask the right question.

**Comment by trippinshrumes** [comment]
Thanks, let me know if you come up with anything and I'll do the same

**Comment by albfan** [comment]
That is a functionality of gnome shell extension "dash to dock"

https://micheleg.github.io/dash-to-dock/settings.html

For whatever reason terminator is not listed on:

https://github.com/micheleg/dash-to-dock/blob/master/dash.js#L702

    this._appSystem.get_running();

You can get support opening a bug on gnome bugzilla or joining us on https://riot.im/app/#/room/#gnome-shell:matrix.org

**Comment by albfan** [comment]
![captura de pantalla de 2017-11-21 20-11-34](https://user-images.githubusercontent.com/220968/33091748-4c70a97a-cef8-11e7-835e-52a575a46af5.png)

After install dash to dock and activate shot dot on running applications it is showing

I'm on arch linux, just can recommend you to update your extensions and distro
