### ISSUE TITLE
Terminator i3-workspace conflicts

### ISSUE THREAD

**Issue by afrat** [albfan/terminator#13]
when I open Terminator in combination with i3-wm it always opens on workspace 1 instead of the focused one. All other terminals work well with i3, so I think it's an issue with terminator but I really don't know.

**Comment by albfan** [comment]
See this is not an official terminator repo. I can help you to triage the problem if you describe the steps to reproduce, (i don't know what a workspace is)

So maybe a screencast is worth. Show 1 use case when it works correctly (say with gnome-terminal) and other with terminator.

Add as much info as possible (distro and versions)

**Comment by afrat** [comment]
While i tried to explain my setup here I found a workaround ;) when i disable the the d-bus-server option in the preferences the terminal starts on the correct workspace. Thanks for rubber ducking ;)

**Comment by albfan** [comment]
yw
