### ISSUE TITLE
Tmux Killer: Allow prefix to Keybindings

### ISSUE THREAD

**Issue by NGenetzky** [albfan/terminator#14]
I was sick of Gnome Terminal and I stumbled across Terminator. From the little research I've done I think I'm ready to make the switch. It seems like Terminator provides a lot of the same functionality I currently use Tmux for. 

Would you consider a feature request for adding a an optional prefix to Keybindings? I am an avid vim user and I have loved having simple Tmux key-bindings since it uses a prefix.

**Comment by albfan** [comment]
This is not official terminator repo. If you're able to modify the code you need to provide the patch on bazaar (launchpad)

I have one PR open for a long time on bazaar, and it is not merged yet.

Please close this if you cannot modify on your own. I can help you if you want to try

**Comment by NGenetzky** [comment]
@albfan, thanks for the quick response.

Please update your github repo description to indicate that this is a fork of "__.git" repo. Gross, I just saw that the project uses Bazaar. I guess just point to the launchpad.

I will simply close this. I will try using it for a while before I try to submit any changes. It is feasible though, I am pretty capable in python.

**Comment by albfan** [comment]
These use to have a README.md pointing it is a fork. (because it allows to fetch from bazaar with a script). Seems I rebased changes for a PR on terminator.

Let me change that to have that README.md again

**Comment by NGenetzky** [comment]
I would recommend you use the Github Description field instead of modifying the README.md which is part of the git repo itself.

**Comment by albfan** [comment]
No, README is part of it. README.md is not

I have rework my changes to sync with bzr easily on master, I recommend to use it, as bazaar is a total mess.

I have added too a link to official repo on description

**Comment by albfan** [comment]
Done!
