### ISSUE TITLE
Terminal width broken when entering docker containers

### ISSUE THREAD

**Issue by chrisscotweb** [albfan/terminator#16]
When entering any docker container (ie, docker exec -ti [container] bash), the terminal width obtained by docker is incorrect.  This leads to very buggy display issues that persist until the terminal window is resized in some way, from that point onwards it's fine.

Unclear as to whether this is a Terminator bug or a docker bug.

![terminator-docker-bug](https://user-images.githubusercontent.com/9747728/39257268-0c0a0ef0-48a9-11e8-8746-e2e52da8265c.png)

terminator 1.91
Docker version 17.12.1-ce, build 7390fc6

**Comment by albfan** [comment]
I have seen that before, but has nothing to do with terminator.

I guess it is running a basic terminal by default
run bash direct after log in an you should see a full terminal (maybe with colors altered)

I think your screenshot is vim, isn't it?

    $ bash
    $ vim <your-file>

should work much better

**Comment by chrisscotweb** [comment]
Sure, a docker problem then.
Rather than have to run 'bash' every time I enter, I used this method for entering instead:
    
    docker exec -it <container> bash -c "stty cols $COLUMNS rows $LINES && bash";

Which solves the problem for me.

Thanks!
