### ISSUE TITLE
Change profile cursor and highlight color

### ISSUE THREAD

**Issue by MParvin** [albfan/terminator#21]
In Terminator config/Profile/Colors there is not option to change cursor color and highlight color.
In some profile colors cannot see some texts.
Please see this file, some files are disappear : 
![Screenshot from 2020-01-04 15-25-40](https://user-images.githubusercontent.com/7812338/71765171-866fbb00-2f06-11ea-8884-1c2493254b5a.png)

**Comment by albfan** [comment]
Sorry this is not a terminator active repo, only a personal fork
